In [7]:
import Data_preprocessing
import Feature_selection
import numpy as np
import pickle
import matplotlib as plt
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import  LogisticRegression
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, f1_score, classification_report
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import learning_curve

In [ ]:
#Using Bag of words features

In [36]:
#Building Naive Bayes Classifier
NB_pipeline=Pipeline([('NBvectorizer',Feature_selection.vectorizer),
                      ('NBclassifier',MultinomialNB())])
#NB_pipeline.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
#predicted_NB=NB_pipeline.predict(Data_preprocessing.test_news['Statement'])
#np.mean(predicted_NB==Data_preprocessing.test_news['Label'])

0.6072128577028616

In [37]:
#Building Logistic Regression Classifier
LR_pipeline=Pipeline([('LRvectorizer',Feature_selection.vectorizer),
                      ('LRclassifier',LogisticRegression())])
#LR_pipeline.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
#predicted_LR=LR_pipeline.predict(Data_preprocessing.test_news['Statement'])
#np.mean(predicted_LR==Data_preprocessing.test_news['Label'])

0.59858878871030963

In [38]:
#Building Linear SVM Classifier
SVM_pipeline=Pipeline([('SVMvectorizer',Feature_selection.vectorizer),
                       ('SVMclassifier',svm.LinearSVC())])
#SVM_pipeline.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
#predicted_SVM=SVM_pipeline.predict(Data_preprocessing.test_news['Statement'])
#np.mean(predicted_SVM==Data_preprocessing.test_news['Label'])

0.57232457859662877

In [105]:
#Building Linear SGD Classifier
SGD_pipeline=Pipeline([('SGDvectorizer',Feature_selection.vectorizer),
                       ('SGDclassifier',SGDClassifier(loss='hinge',alpha=1e-3,max_iter=5))])
#SGD_pipeline.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
#predicted_SGD=SGD_pipeline.predict(Data_preprocessing.test_news['Statement'])
#np.mean(predicted_SGD==Data_preprocessing.test_news['Label'])

0.60329282634261072

In [45]:
#Building Random Foreset Classifier
RF_pipeline=Pipeline([('RFvectorizer',Feature_selection.vectorizer),
                      ('RFclassifier',RandomForestClassifier(n_estimators=200,n_jobs=3))])
#RF_pipeline.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
#predicted_RF=RF_pipeline.predict(Data_preprocessing.test_news['Statement'])
#np.mean(predicted_RF==Data_preprocessing.test_news['Label'])

0.61858094864758917

In [59]:
#Improve performance by using K-Fold Cross Validation
#Build Confusion Matrix to analysis the performance of different Classifiers
def build_confusion_matrix(classifier,split_num):
    k_fold=KFold(n_splits=split_num)
    scores=[]
    Confusion_Matrix=[[0,0],[0,0]]
    for train_ind,test_ind in k_fold.split(Data_preprocessing.train_news):
        train_text=Data_preprocessing.train_news.iloc[train_ind]['Statement']
        train_y=Data_preprocessing.train_news.iloc[train_ind]['Label']
        test_text=Data_preprocessing.train_news.iloc[test_ind]['Statement']
        test_y=Data_preprocessing.train_news.iloc[test_ind]['Label']
        classifier.fit(train_text,train_y)
        predictions=classifier.predict(test_text)
        Confusion_Matrix+=confusion_matrix(test_y,predictions)
        scores.append(f1_score(test_y,predictions))
    return (print('Total statements classified:', len(Data_preprocessing.train_news)),
            print('Score:', sum(scores)/len(scores)),
            print('score length', len(scores)),
            print('Confusion matrix:'),
            print(Confusion_Matrix))
#build_confusion_matrix(classifier,split_num)

In [72]:
#build_confusion_matrix(NB_pipeline,7)

Total statements classified: 10240
Score: 0.675071936487
score length 7
Confusion matrix:
[[2130 2358]
 [1619 4133]]


(None, None, None, None, None)

In [79]:
#build_confusion_matrix(LR_pipeline,6)

Total statements classified: 10240
Score: 0.647679059498
score length 6
Confusion matrix:
[[2230 2258]
 [1915 3837]]


(None, None, None, None, None)

In [84]:
#build_confusion_matrix(SVM_pipeline,7)

Total statements classified: 10240
Score: 0.614367797118
score length 7
Confusion matrix:
[[2249 2239]
 [2208 3544]]


(None, None, None, None, None)

In [85]:
#build_confusion_matrix(RF_pipeline,6)

Total statements classified: 10240
Score: 0.703094560493
score length 6
Confusion matrix:
[[1812 2676]
 [1183 4569]]


(None, None, None, None, None)

In [ ]:
#Using N-grams

In [124]:
#Building Naive Bayes Classifier
NB_pipeline_ngram=Pipeline([('NBnvectorizer',Feature_selection.tfidf_ngram),
                      ('NBnclassifier',MultinomialNB())])
#NB_pipeline_ngram.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
#predicted_NB_ngram=NB_pipeline_ngram.predict(Data_preprocessing.test_news['Statement'])
#np.mean(predicted_NB_ngram==Data_preprocessing.test_news['Label'])

0.59388475107800864

In [3]:
#Building Logistic Regression Classifier
LR_pipeline_ngram=Pipeline([('LRnvectorizer',Feature_selection.tfidf_ngram),
                      ('LRnclassifier',LogisticRegression(penalty="l2",C=1))])
LR_pipeline_ngram.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
predicted_LR_ngram=LR_pipeline_ngram.predict(Data_preprocessing.test_news['Statement'])
np.mean(predicted_LR_ngram==Data_preprocessing.test_news['Label'])

0.61936495491963939

In [94]:
#Building Linear SVM Classifier
SVM_pipeline_ngram=Pipeline([('SVMvectorizer',Feature_selection.tfidf_ngram),
                       ('SVMclassifier',svm.LinearSVC())])
#SVM_pipeline_ngram.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
#predicted_SVM_ngram=SVM_pipeline_ngram.predict(Data_preprocessing.test_news['Statement'])
#np.mean(predicted_SVM_ngram==Data_preprocessing.test_news['Label'])

0.61701293610348884

In [130]:
#Building Linear SGD Classifier
SGD_pipeline_ngram=Pipeline([('SGDvectorizer',Feature_selection.tfidf_ngram),
                       ('SGDclassifier',SGDClassifier(loss='hinge',alpha=1e-3,max_iter=5))])
#SGD_pipeline_ngram.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
#predicted_SGD_ngram=SGD_pipeline_ngram.predict(Data_preprocessing.test_news['Statement'])
#np.mean(predicted_SGD_ngram==Data_preprocessing.test_news['Label'])

0.54174833398667188

In [95]:
#Building Random Foreset Classifier
RF_pipeline_ngram=Pipeline([('RFvectorizer',Feature_selection.tfidf_ngram),
                      ('RFclassifier',RandomForestClassifier(n_estimators=200,n_jobs=3))])
#RF_pipeline_ngram.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
#predicted_RF_ngram=RF_pipeline_ngram.predict(Data_preprocessing.test_news['Statement'])
#np.mean(predicted_RF_ngram==Data_preprocessing.test_news['Label'])

0.59662877303018425

In [116]:
#build_confusion_matrix(NB_pipeline_ngram,5)

Total statements classified: 10240
Score: 0.722405315984
score length 5
Confusion matrix:
[[ 758 3730]
 [ 390 5362]]


(None, None, None, None, None)

In [110]:
#build_confusion_matrix(LR_pipeline_ngram,6)

Total statements classified: 10240
Score: 0.702698007278
score length 6
Confusion matrix:
[[1584 2904]
 [1063 4689]]


(None, None, None, None, None)

In [121]:
#build_confusion_matrix(SVM_pipeline_ngram,6)

Total statements classified: 10240
Score: 0.679655893649
score length 6
Confusion matrix:
[[2024 2464]
 [1523 4229]]


(None, None, None, None, None)

In [122]:
#build_confusion_matrix(SGD_pipeline_ngram,6)

Total statements classified: 10240
Score: 0.719247218409
score length 6
Confusion matrix:
[[   1 4487]
 [   1 5751]]


(None, None, None, None, None)

In [123]:
#build_confusion_matrix(RF_pipeline_ngram,6)

Total statements classified: 10240
Score: 0.658660060206
score length 6
Confusion matrix:
[[2021 2467]
 [1715 4037]]


(None, None, None, None, None)

In [126]:
#print(classification_report(Data_preprocessing.test_news['Label'], predicted_NB_ngram))

             precision    recall  f1-score   support

      False       0.72      0.19      0.30      1169
       True       0.58      0.94      0.71      1382

avg / total       0.64      0.59      0.52      2551



In [127]:
#print(classification_report(Data_preprocessing.test_news['Label'], predicted_LR_ngram))

             precision    recall  f1-score   support

      False       0.64      0.39      0.49      1169
       True       0.61      0.81      0.70      1382

avg / total       0.62      0.62      0.60      2551



In [128]:
#print(classification_report(Data_preprocessing.test_news['Label'], predicted_SVM_ngram))

             precision    recall  f1-score   support

      False       0.61      0.47      0.53      1169
       True       0.62      0.74      0.68      1382

avg / total       0.62      0.62      0.61      2551



In [132]:
#print(classification_report(Data_preprocessing.test_news['Label'], predicted_SGD_ngram))

In [133]:
print(classification_report(Data_preprocessing.test_news['Label'], predicted_RF_ngram))

             precision    recall  f1-score   support

      False       0.57      0.47      0.52      1169
       True       0.61      0.70      0.65      1382

avg / total       0.59      0.60      0.59      2551



In [150]:
#Choose LR and SVM as candidate models
#Find optimal parameters for LR
LR_parameters = {'LR_tfidf__ngram_range': [(1,1),(1, 2),(1,3),(1,4),(1,5)],
                 'LR_tfidf__use_idf': (True, False),
                 'LR_tfidf__smooth_idf': (True, False)}
LR_gop = GridSearchCV(LR_pipeline_ngram, parameters, n_jobs=-1)
LR_gop = LR.gop.fit(Data_preprocessing.train_news['Statement'][:10000],Data_preprocessing.train_news['Label'][:10000])
#LR_gop.best_score_
#LR_gop.best_params_
#LR_gop.cv_results_

In [151]:
#Find optimal parameters for SVM
SVM_parameters = {'SVM_tfidf__ngram_range': [(1,1),(1,2),(1,3),(1,4),(1,5)],
                  'SVM_tfidf__use_idf': (True, False),
                  'SVM_tfidf__smooth_idf': (True, False),
                  'SVM_clf__penalty': ('l1','l2'),}
SVM_gop = GridSearchCV(SVM_pipeline_ngram, parameters, n_jobs=-1)
SVM_gop= SVM_gop.fit(DataPrep.train_news['Statement'][:10000],DataPrep.train_news['Label'][:10000])
#LR_gop.best_score_
#LR_gop.best_params_
#LR_gop.cv_results_

In [153]:
LR_pipeline_final = Pipeline([
    ('LR_tfidf',TfidfVectorizer(stop_words='english',ngram_range=(1,5),use_idf=True,smooth_idf=False)),
    ('LRclassifier',LogisticRegression(penalty="l2",C=1))
])

In [154]:
#Testing Final Model
LR_pipeline_final.fit(Data_preprocessing.train_news['Statement'],Data_preprocessing.train_news['Label'])
predicted_LR_final = LR_pipeline_final.predict(Data_preprocessing.test_news['Statement'])
np.mean(predicted_LR_final == Data_preprocessing.test_news['Label'])

0.61779694237553895

In [157]:
print(classification_report(Data_preprocessing.test_news['Label'], predicted_LR_final))

             precision    recall  f1-score   support

      False       0.64      0.38      0.48      1169
       True       0.61      0.82      0.70      1382

avg / total       0.62      0.62      0.60      2551



In [4]:
#Saving chosen model
file = 'best_model.sav'
pickle.dump(LR_pipeline_ngram,open(file,'wb'))